【翻译完成】20200801-Go-How-to-Reduce-Lock-Contention-with-the-Atomic-Package
studygolang/GCTT pull request #1821
Opened 2020-09-16 05:08 UTC by double12gzh

close #1805

2020-09-28 16:24 UTC, lxbwolf commented
所有的英文和中文中间，加一个空格
题目：如何使用atomic包减少锁冲突

2020-09-29 00:44 UTC, lxbwolf requested changes
原文有更新，辛苦更新下译文内容

2020-09-29 00:44 UTC, lxbwolf commented on translated/tech/20200801-Go-How-to-Reduce-Lock-Contention-with-the-Atomic-Package.md
> +当两个或两个以上的goroutine同时访问同一块内存区域，并且其中至少有一个在写时，就会发生数据竞争。虽然`map`有内部有一定的机制来防止数据竞争，但一个简单的结构体并没有任何的机制，因此容易发生数据竞争。
`map`有内部有一定
=> `map`~~有~~内部有一定

2020-09-29 00:44 UTC, lxbwolf commented on translated/tech/20200801-Go-How-to-Reduce-Lock-Contention-with-the-Atomic-Package.md
> +为了说明数据竞争，我以一个**goroutine持续更新的配置**为例向大家展示一下。
**goroutine持续更新的配置**为
=> goroutine持续更新的配置为

2020-09-29 00:44 UTC, lxbwolf commented on translated/tech/20200801-Go-How-to-Reduce-Lock-Contention-with-the-Atomic-Package.md
> +标准库为`sync`包提供了两种`mutex`：**sync.Mutex**和**sync.RWMutex**。后者在你的程序需要处理多个读操作和极少的写操作时进行了优化。
标准库为`sync`包提供了两种`mutex`：**sync.Mutex**和**sync.RWMutex**
=> 标准库在 `sync` 包中提供了两种互斥锁：`sync.Mutex` 和 `sync.RWMutex`

2021-12-26 12:50 UTC, merged

2021-12-26 12:51 UTC, polaris1119 commented
直接按照校对修改