【翻译完成】20200912-Optimizing-String-Comparisons-in-Go
studygolang/GCTT pull request #1832
Opened 2020-11-02 16:33 UTC by lxbwolf

close #1831

2020-11-05 12:41 UTC, polaris1119 requested changes
一些小点要改下

2020-11-05 12:41 UTC, polaris1119 commented on translated/tech/20200912-Optimizing-String-Comparisons-in-Go.md
> +首先，我们会起一个独立的 app 外加一个测试文件。我们会使用 Go 测试工具中的<ruby>基准测试工具<rt>Benchmarking utility</rt></ruby>。
```suggestion
首先，我们创建一个带有测试文件的应用。我们将使用 Go 测试工具中的 Benchmarking 实用工具。
```

2020-11-05 12:41 UTC, polaris1119 commented on translated/tech/20200912-Optimizing-String-Comparisons-in-Go.md
> +它们耗时耗时一样的。但是为什么呢？
```suggestion
它们耗时是一样的。但是为什么呢？
```

2020-11-05 13:17 UTC, lxbwolf commented
> 一些小点要改下

已修正

2020-11-06 01:31 UTC, polaris1119 approved these changes

2020-11-06 01:31 UTC, merged