【翻译完成】20200901 Go: Multiple Errors Management
studygolang/GCTT pull request #1842
Opened 2020-11-21 13:36 UTC by dust347

close #1827

2021-04-14 09:19 UTC, polaris1119 requested changes
一些小的问题

2021-04-14 09:19 UTC, polaris1119 commented on translated/tech/20200901-Go-Multiple-Errors-Management.md
> +Uber 的实现略慢，同事消耗更多内存。但是，这个包被设计为一次将错误聚合在一起，而不是每次都追加它们。在聚合 error 的时候，结果是接近的。但是由于需要额外步骤，代码有点不太优雅。这是新的结果：
同事 -> 同时

2021-04-14 09:19 UTC, polaris1119 commented on translated/tech/20200901-Go-Multiple-Errors-Management.md
> +来以一个程序开始，该程序使用多个 goroutine 执行一系列行为（action）；每个行为持续一秒：
来以一个程序开始 -> 来 字可以删除吧

2021-04-14 09:19 UTC, polaris1119 commented on translated/tech/20200901-Go-Multiple-Errors-Management.md
> +然而，我们可能希望使 goroutine 之间相互依赖，并且如果其中一个失败就取消他们。避免无谓工作的解决方案可以是加一个 context，并且，一旦一个 goroutine 失败，它就会取消它：
```suggestion
然而，我们可能希望使 goroutine 之间相互依赖，并且如果其中一个失败就取消他们。避免无谓工作的解决方案可以是加一个 context，并且，一旦一个 goroutine 失败，就会取消它：
```

2021-04-19 02:48 UTC, dust347 commented on translated/tech/20200901-Go-Multiple-Errors-Management.md
> +Uber 的实现略慢，同事消耗更多内存。但是，这个包被设计为一次将错误聚合在一起，而不是每次都追加它们。在聚合 error 的时候，结果是接近的。但是由于需要额外步骤，代码有点不太优雅。这是新的结果：
已修改

2021-04-19 02:48 UTC, dust347 commented on translated/tech/20200901-Go-Multiple-Errors-Management.md
> +来以一个程序开始，该程序使用多个 goroutine 执行一系列行为（action）；每个行为持续一秒：
已修改

2021-04-19 02:48 UTC, dust347 commented on translated/tech/20200901-Go-Multiple-Errors-Management.md
> +然而，我们可能希望使 goroutine 之间相互依赖，并且如果其中一个失败就取消他们。避免无谓工作的解决方案可以是加一个 context，并且，一旦一个 goroutine 失败，它就会取消它：
已修改

2021-05-07 14:04 UTC, merged